# Generated by Django 3.1.2 on 2020-11-14 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0010_auto_20201114_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pinterest_url',
            new_name='linkedin_url',
        ),
    ]
